using System;

namespace GameEngine
{
    /// <summary>
    /// Events generated by the game
    /// </summary>
    static partial class Advent
    {

        public static event EventHandler<GameOuput> GameView;

        /// <summary>
        /// Display the room view - items and description
        /// </summary>
        private static void onUpdateView()
        {
            GameView(null, new GameOuput(_RoomView, true));
        }

        public static event EventHandler<GameOuput> GameOutput;

        /// <summary>
        /// Send a message out
        /// </summary>
        /// <param name="pMessage">Message to display</param>
        /// <param name="pClearOutput">Clear output before displaying message</param>
        private static void SetGameOutput(string pMessage, bool pClearOutput)
        {
            GameOutput(null, new GameOuput(pMessage, pClearOutput));
        }


        public class GameOuput : EventArgs
        {
            public string Message { get; private set; }
            public bool Refresh { get; private set; }

            public GameOuput(string pMessage, bool pRefresh)
            {
                Message = pMessage;
                Refresh = pRefresh;
            }
        }

    }
}
